# This is for development only. Do not use this in production.

version: '3'
services:
  tailproxy:
    build: .
    environment:
      - TAILPROXY_HTTPS_MODE=${TAILPROXY_HTTPS_MODE}
      - TAILPROXY_NAME=tailproxy
      - TAILPROXY_TARGET=test_server:8000
      - TAILPROXY_PPROF_ENABLED=${TAILPROXY_PPROF_ENABLED}
      - TS_AUTHKEY=${TS_AUTHKEY}
    volumes:
      - ./tailproxy-data:/home/nonroot/data
    links:
      - test_server
  test_server:
    build: ./test-server
