name: Build Docker Image

on:
  push:
    branches: [main]
    tags: [v*]
    paths-ignore:
      - README.md
      - LICENSE.txt

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - uses: ko-build/setup-ko@v0.6

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/j-f1/tailproxy
          flavor: latest=auto
          tags: |
            type=semver,pattern=v{{major}}
            type=semver,pattern={{raw}}
            type=edge,value=edge
            type=sha

      - name: Rewrite tags
        id: tags
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          echo "$TAGS" | awk -F: '{print $2}' | paste -sd, - > tags.txt
          echo "::group::Tags"
          cat tags.txt
          echo "::endgroup::"
          echo "tags=$(cat tags.txt)" >> $GITHUB_OUTPUT

      - run: ko build --bare --tags=${{ steps.tags.outputs.tags }} --platform=all
